import { Link } from 'react-router-dom';
import { ArrowUpRight, ChevronRight, CircleAlert, CircleCheck, Info, Radio, Activity } from 'lucide-react';
import type { ReactNode } from 'react';
export function Brand({ light = false }: { light?: boolean }) { return <Link to="/" className={`brand ${light ? 'brand-light' : ''}`} aria-label="IDHTM home"><img className="brand-logo" src="/assets/images/branding/idhtm-logo-clean.png" alt="" aria-hidden="true" /><span><strong>IDHTM</strong><small>Drone intelligence</small></span></Link>; }
export function Eyebrow({ children }: { children: ReactNode }) { return <div className="eyebrow"><span className="eyebrow-line" />{children}</div>; }
export function StatusPill({ label, tone = 'green' }: { label: string; tone?: 'green'|'amber'|'red'|'blue'|'gray' }) { return <span className={`status-pill ${tone}`}><span className="status-dot" />{label}</span>; }
export function Metric({ label, value, unit, note, tone = 'default' }: { label: string; value: string|number; unit?: string; note?: string; tone?: string }) { return <div className={`metric ${tone}`}><span className="metric-label">{label}</span><strong>{value}<small>{unit}</small></strong>{note && <span className="metric-note">{note}</span>}</div>; }
export function ScoreBar({ score, tone = 'blue' }: { score: number; tone?: 'blue'|'green'|'amber'|'red' }) { return <div className={`score-bar ${tone}`} role="meter" aria-valuemin={0} aria-valuemax={100} aria-valuenow={score} aria-label={`Health score ${score} out of 100`}><span style={{ width: `${Math.max(0, Math.min(100, score))}%` }} /></div>; }
export function Sparkline({ points, color = '#2364a1' }: { points: number[]; color?: string }) { const max = Math.max(...points), min = Math.min(...points); const path = points.map((p, i) => `${i ? 'L' : 'M'} ${(i/(points.length-1))*100} ${100 - ((p-min)/(max-min || 1))*76 - 12}`).join(' '); return <svg className="sparkline" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d={path} fill="none" stroke={color} strokeWidth="2.5" vectorEffect="non-scaling-stroke" /></svg>; }
export function SectionHeading({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy?: string; action?: ReactNode }) { return <div className="section-heading"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{copy && <p>{copy}</p>}</div>{action}</div>; }
export function EmptyState({ title, copy, action }: { title: string; copy: string; action?: ReactNode }) { return <div className="empty-state"><div className="empty-icon"><Radio size={20}/></div><h3>{title}</h3><p>{copy}</p>{action}</div>; }
export function AlertRow({ title, explanation, severity, metric, recommendation, timestamp, acknowledged, onAcknowledge }: { title: string; explanation: string; severity: string; metric: string; recommendation: string; timestamp: string; acknowledged?: boolean; onAcknowledge?: () => void }) { const Icon = severity === 'CRITICAL' ? CircleAlert : severity === 'WARNING' ? Info : CircleCheck; return <div className={`alert-row ${severity.toLowerCase()}`}><div className="alert-icon"><Icon size={16}/></div><div className="alert-body"><div className="alert-top"><span className="alert-severity">{severity}</span><time>{timestamp}</time></div><h4>{title}</h4><p>{explanation}</p><div className="alert-meta"><span>Current value <strong>{metric}</strong></span><span className="recommendation"><ArrowUpRight size={13}/> {recommendation}</span></div></div>{onAcknowledge && <button className="text-button" onClick={onAcknowledge}>{acknowledged ? 'Acknowledged' : 'Acknowledge'}</button>}</div>; }
export function Chart({ type = 'line', points, labels = false }: { type?: 'line'|'area'; points: number[]; labels?: boolean }) { const max = Math.max(...points), min = Math.min(...points); const path = points.map((p, i) => `${i ? 'L' : 'M'} ${(i/(points.length-1))*100} ${100 - ((p-min)/(max-min || 1))*78 - 8}`).join(' '); return <div className="chart-wrap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="chart"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#2364a1" stopOpacity=".18"/><stop offset="1" stopColor="#2364a1" stopOpacity="0"/></linearGradient></defs>{[20,45,70].map(y => <line key={y} x1="0" x2="100" y1={y} y2={y} stroke="#d9dfe5" strokeWidth=".35"/>)}{type === 'area' && <path d={`${path} L 100 100 L 0 100 Z`} fill="url(#chartFill)"/>}<path d={path} fill="none" stroke="#2364a1" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></svg>{labels && <div className="chart-labels"><span>−24h</span><span>−12h</span><span>Now</span></div>}</div>; }